name: Validate plugins.json

on:
  pull_request:
    paths:
      - 'plugins.json'

jobs:
  json-yaml-validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    - name: json-yaml-validate
      id: json-yaml-validate
      uses: GrantBirki/json-yaml-validate@v2.3.1
      with:
        files: 'plugins.json'
        json_schema: '.github/workflows/json-schema/schema.json'
        comment: 'true'
        json_schema_version: "draft-2019-09"